<a href="https://colab.research.google.com/github/RamadeviKN/MachineLearningUsingPythonAndR/blob/main/ml_zoomcamp_hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.1.4'

In [4]:
df=pd.read_csv('laptops.csv')
print(df)

                                                 Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RA

In [5]:
df_count = df.count()[0]
print(df_count)

2160


<ipython-input-5-bb574f264578>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_count = df.count()[0]


In [6]:
df.Brand.nunique()

27

In [7]:
df.nunique()[2]

<ipython-input-7-9d85f5dc7397>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.nunique()[2]


27

In [8]:
df.isnull().any().sum()

3

In [9]:
max_price = df[df['Brand'] == 'Dell']['Final Price'].max()
print(max_price)

3936.0


In [10]:
m1=df['Screen'].median()
freq_value=df['Screen'].mode()
df['Screen'] = df['Screen'].fillna(freq_value)
m2=df['Screen'].median()
if m1==m2:
    print('Not Changed')
else:
    print('Changed')

Not Changed


In [11]:
innjoo_brand_df = df[df['Brand'] == 'Innjoo'] [['RAM','Storage','Screen']]
print(innjoo_brand_df)
import numpy as np
X= np.array(innjoo_brand_df)
print(X)

      RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1
[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [15]:
XTX=np.array(X.T)
print(XTX)

[[  8.    8.    4.    6.    6.    6. ]
 [256.  512.   64.   64.  128.  128. ]
 [ 15.6  15.6  14.1  14.1  14.1  14.1]]


In [16]:
product=X.dot(XTX)
print(product)

[[ 65843.36 131379.36  16635.96  16651.96  33035.96  33035.96]
 [131379.36 262451.36  33019.96  33035.96  65803.96  65803.96]
 [ 16635.96  33019.96   4310.81   4318.81   8414.81   8414.81]
 [ 16651.96  33035.96   4318.81   4330.81   8426.81   8426.81]
 [ 33035.96  65803.96   8414.81   8426.81  16618.81  16618.81]
 [ 33035.96  65803.96   8414.81   8426.81  16618.81  16618.81]]


In [17]:
XTX_inv = np.linalg.pinv(XTX)
print(XTX_inv)

[[ 0.26298349 -0.00110155 -0.08772226]
 [-0.12560233  0.00295059  0.0269791 ]
 [-0.40646389  0.00125892  0.17140891]
 [ 0.14958687 -0.00177691 -0.0302108 ]
 [ 0.05244042 -0.00076387 -0.00153546]
 [ 0.05244042 -0.00076387 -0.00153546]]


In [23]:
y=np.array([1100, 1300, 800, 900, 1000, 1100])
print(y)

[1100 1300  800  900 1000 1100]


In [24]:
prod_value=XTX_inv.dot(X.T)
print(prod_value)
w=prod_value.dot(y)
print(w)

[[ 0.45340318  0.17140569 -0.25544928  0.2705177   0.20001833  0.20001833]
 [ 0.17140569  0.92675609  0.06683356 -0.1843711   0.0044665   0.0044665 ]
 [-0.25544928  0.06683356  0.87158079  0.05865301  0.13922372  0.13922372]
 [ 0.2705177  -0.1843711   0.05865301  0.35782675  0.24410455  0.24410455]
 [ 0.20001833  0.0044665   0.13922372  0.24410455  0.1952166   0.1952166 ]
 [ 0.20001833  0.0044665   0.13922372  0.24410455  0.1952166   0.1952166 ]]
[1180.71589468 1290.24170248  848.31155551  939.47308763  966.85453958
  966.85453958]


In [26]:
print(np.sum(w))

6192.45131945146
