<a href="https://colab.research.google.com/github/RamadeviKN/MachineLearningUsingPythonAndR/blob/main/ml_zoomcamp_hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Statement

In [27]:
import pandas as pd

Pandas Version

In [2]:
pd.__version__

'2.1.4'

Reading CSV dataset

In [4]:
df=pd.read_csv('laptops.csv')
print(df)

                                                 Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RA

Record count - How many records are in the dataset?

In [5]:
df_count = df.count()[0]
print(df_count)

2160


<ipython-input-5-bb574f264578>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_count = df.count()[0]


Laptop Brands - How many laptop brands are presented in the dataset?

In [6]:
df.Brand.nunique()

27

In [7]:
df.nunique()[2]

<ipython-input-7-9d85f5dc7397>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.nunique()[2]


27

Missing Values - How many columns in the dataset have missing values?

In [8]:
df.isnull().any().sum()

3

Maximum Final Price value - What's the maximum final price of Dell notebooks in the dataset?

In [28]:
max_dell_price = df[df['Brand'] == 'Dell']['Final Price'].max()
print(max_dell_price)

3936.0


Median value of Screen

In [10]:
m1=df['Screen'].median()
freq_value=df['Screen'].mode()
df['Screen'] = df['Screen'].fillna(freq_value)
m2=df['Screen'].median()
if m1==m2:
    print('Not Changed')
else:
    print('Changed')

Not Changed


Sum of weights

In [54]:
innjoo_brand_df = df[df['Brand'] == 'Innjoo'] [['RAM','Storage','Screen']]
print(innjoo_brand_df)
import numpy as np
X= innjoo_brand_df.to_numpy()
print(X)

      RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1
[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [56]:
XTX = np.dot(X.T, X)
print(XTX)

[[2.52000e+02 8.32000e+03 5.59800e+02]
 [8.32000e+03 3.68640e+05 1.73952e+04]
 [5.59800e+02 1.73952e+04 1.28196e+03]]


In [58]:
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

[[ 2.78025381e-01 -1.51791334e-03 -1.00809855e-01]
 [-1.51791334e-03  1.58286725e-05  4.48052175e-04]
 [-1.00809855e-01  4.48052175e-04  3.87214888e-02]]


In [59]:
y=np.array([1100, 1300, 800, 900, 1000, 1100])
print(y)

[1100 1300  800  900 1000 1100]


In [60]:
w = np.dot(np.dot(XTX_inv, X.T), y)
print(w)

[45.58076606  0.42783519 45.29127938]


In [61]:
print(np.sum(w))

91.2998806299555
