<a href="https://colab.research.google.com/github/RamadeviKN/MachineLearningUsingPythonAndR/blob/main/numpy_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing Numpy

In [1]:
import numpy as np
np


<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

## Creating Arrays

In [3]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a=np.array(['cat','dog','deer'])
print(a[2])

deer


In [9]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
b=np.arange(3,10)
print(b)

[3 4 5 6 7 8 9]


In [12]:
arr=np.linspace(0,100,11)
print(arr)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


# Multidimensional Arrays

In [13]:
ma=np.zeros((5,2))
print(ma)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [16]:
maa=np.array([
    [9,4,5],
    [0,3,6],
    [4,7,3]
])
print(maa)

[[9 4 5]
 [0 3 6]
 [4 7 3]]


In [17]:
print(maa[1])

[0 3 6]


In [18]:
print(maa[:,2])

[5 6 3]


### Randomly generated arrays

In [19]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [20]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [ ]:
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

## Element-wise Operations

In [22]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
print(a+1)

[ 1  2  3  4  5  6  7  8  9 10]


In [24]:
print(a*3)

[ 0  3  6  9 12 15 18 21 24 27]


In [31]:
b=(10+(a*2))**2
print(b)
print(a+b)
print(a/b*10)

[100 144 196 256 324 400 484 576 676 784]
[100 145 198 259 328 405 490 583 684 793]
[0.         0.06944444 0.10204082 0.1171875  0.12345679 0.125
 0.12396694 0.12152778 0.1183432  0.11479592]


In [33]:
print(a>=2)

[False False  True  True  True  True  True  True  True  True]


In [34]:
print(a>b)

[False False False False False False False False False False]


In [36]:
print(a[a<=b])

[0 1 2 3 4 5 6 7 8 9]


## Summarizing Operations

In [38]:
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(a.std())

0
9
45
4.5
2.8722813232690143
